version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-wp
    environment:
      MYSQL_ROOT_PASSWORD: 311003
      MYSQL_DATABASE: fintech
      MYSQL_USER: samidha
      MYSQL_PASSWORD: 311003
    ports:
      - "3306:3306"
    volumes:
      - ../data:/var/lib/mysql

  php:
    image: php:apache
    container_name: php-wp
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-wp
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql



